### ISSUE TITLE
Error when querying by secondary index and sorting

### ISSUE THREAD

**Issue by thekiwi** [mbroadst/thinky-rest#1]
I'm using thinky-rest 0.1.3 and I've discovered if you have a query that uses the secondary index, as well as sorting, RethinkDB throws an error:
`Expected type TABLE but found SELECTION: SELECTION ON table(foo)`

An example request that causes this error would be:
`http://localhost:3000/api/foo?bar=123&sort=baz`
(where `bar` is the secondary index)

I'm new to RethinkDB but I think this is due to the _applyOrderBy function being executed (and appending `orderBy` to the query) before the secondary index based criteria is added to the query. 

Apart from this, thinky-rest is great! I might have a go forking and creating a PR myself if I get some time.

**Comment by mbroadst** [comment]
@thekiwi hey I've pushed some changes to further optimize queries with secondary indexes, I wonder if you'd have a chance to give it a run in your environment? You're the only other user I currently know of of the module :smile: 

I'm pushing the changes in a point release, and they pass your added test as well as a few others I've added.
